=== VladaGromova/FourthTask/src/main/resources/tariffs.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/tariffs"
        xmlns:tns="http://www.example.com/tariffs" elementFormDefault="qualified">
    <element name="tariff" type="tns:Tariff" abstract="true"/>
    <element name="pensioner-tariff" type="tns:PensionerTariff" substitutionGroup="tns:tariff"/>
    <element name="student-tariff" type="tns:StudentTariff" substitutionGroup="tns:tariff"/>
    <element name="tariffs">
        <complexType>
        <sequence>
            <element name="pensioner-tariff" type="tns:PensionerTariff" minOccurs="2" maxOccurs="unbounded"/>
            <element name="student-tariff" type="tns:StudentTariff" minOccurs="2" maxOccurs="unbounded"/>
        </sequence>
        </complexType>
    </element>
    <complexType name="CallPrices">
        <sequence>
            <element name="in-network" type="positiveInteger"/>
            <element name="out-network" type="positiveInteger"/>
            <element name="stationary" type="positiveInteger"/>
        </sequence>
    </complexType>
    <complexType name="Parameters">
        <sequence>
            <element name="number-of-favourites" type="positiveInteger"/>
            <element name="payment" type="positiveInteger"/>
        </sequence>
        <attribute name="tariffication" use="optional" default="12seconds">
            <simpleType>
                <restriction base="string">
                    <enumeration value="12seconds"/>
                    <enumeration value="1minute"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <complexType name="Tariff" abstract="true">
        <sequence>
            <element name="name" type="string"/>
            <element name="payroll" type="positiveInteger"/>
            <element name="call-prices" type="tns:CallPrices"/>
            <element name="sms-price" type="positiveInteger"/>
            <element name="parameters" type="tns:Parameters"/>
        </sequence>
        <attribute name="operator-name" use="required">
            <simpleType>
                <restriction base="string">
                    <enumeration value="MTS"/>
                    <enumeration value="A"/>
                    <enumeration value="LIFE"/>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <simpleType name="Login">
        <restriction base="ID">
            <pattern value="([a-zA-Z])[a-zA-Z0-9]{7,19}"/>
        </restriction>
    </simpleType>
    <complexType name="StudentTariff">
        <complexContent>
            <extension base="tns:Tariff">
                <attribute name="login" type="tns:Login" use="required"/>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="PensionerTariff">
        <complexContent>
            <extension base="tns:Tariff">
                <sequence>
                    <element name="discount-percent" type="positiveInteger"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>
</schema>

=== VladaGromova/FourthTask/src/main/resources/tariffs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.example.com/tariffs" xsi:schemaLocation="http://www.example.com/tariffs tariffs.xsd">
    <pensioner-tariff operator-name="MTS">
        <name>SixtyPlus</name>
        <payroll>60</payroll>
        <call-prices>
            <in-network>1</in-network>
            <out-network>3</out-network>
            <stationary>3</stationary>
        </call-prices>
        <sms-price>2</sms-price>
        <parameters>
            <number-of-favourites>5</number-of-favourites>
            <payment>20</payment>
        </parameters>
        <discount-percent>3</discount-percent>
    </pensioner-tariff>
    <pensioner-tariff operator-name="LIFE">
        <name>LifeStartsNow</name>
        <payroll>40</payroll>
        <call-prices>
            <in-network>4</in-network>
            <out-network>4</out-network>
            <stationary>4</stationary>
        </call-prices>
        <sms-price>2</sms-price>
        <parameters tariffication="1minute">
            <number-of-favourites>4</number-of-favourites>
            <payment>14</payment>
        </parameters>
        <discount-percent>4</discount-percent>
    </pensioner-tariff>
    <student-tariff operator-name="MTS" login="RayJohn7">
        <name>Chill</name>
        <payroll>70</payroll>
        <call-prices>
            <in-network>1</in-network>
            <out-network>2</out-network>
            <stationary>3</stationary>
        </call-prices>
        <sms-price>4</sms-price>
        <parameters tariffication="12seconds">
            <number-of-favourites>10</number-of-favourites>
            <payment>15</payment>
        </parameters>
    </student-tariff>
    <student-tariff operator-name="A" login="MullerAlex7">
        <name>StudyEasy</name>
        <payroll>50</payroll>
        <call-prices>
            <in-network>2</in-network>
            <out-network>2</out-network>
            <stationary>2</stationary>
        </call-prices>
        <sms-price>1</sms-price>
        <parameters tariffication="1minute">
            <number-of-favourites>3</number-of-favourites>
            <payment>25</payment>
        </parameters>
    </student-tariff>
</tariffs>
